  version: '3'

  services:
    db:
      restart: always
      volumes:
        - ./db/:/var/lib/postgresql/data/
      image: postgres:12.3
      env_file:
        - ./env/env.env
      container_name: fr_db
    web:
      build: .
      command: gunicorn -t 180 -w 3 frtest.wsgi:application --bind 0.0.0.0:8000
      restart: always
      env_file:
        - ./env/env.env
      volumes:
        - ./static:/code/static
      expose:
        - 8000
      depends_on:
        - db
      container_name: fr_web
    nginx:
      build: ./nginx
      restart: always
      container_name: fr_nginx
      volumes:
        - ./static:/code/static
      ports:
        - 1354:80
      depends_on:
        - web
        - db
